name: Cleanup Untagged Images

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
        default: ${{ github.repository_owner }}

      registry:
        required: true
        type: string

      image:
        required: false
        type: string
        default: ${{ github.repository }}

    secrets:
      GH_PCKG_TOKEN:
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Clean up

    steps:
      - name: Extract Image Name
        run: |
          echo "PACKAGE_NAME=${{ inputs.image }}" 
          echo "PACKAGE_NAME=${PACKAGE_NAME#*/}" >> $GITHUB_ENV
    
      - name: Cleanup Images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          registry-url: https://${{ inputs.registry }}/
          token: ${{ secrets.GH_PCKG_TOKEN }}
          owner: ${{ inputs.username }}
          package: ${{ env.PACKAGE_NAME }}
          delete-tags: sha-*
          delete-untagged: true
          delete-orphaned-images: true
